spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:employee_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres_pass}
  batch:
    job:
      # Spring Batch executes all jobs by default. This property disables that behavior.
      # This is needed as we want to trigger the jobs manually.
      enabled: false